# Site settings
title: LiEmail
header-img: "img/autumn2.jpg"
tagline: "记忆宫殿"  
description: "Li不清楚 模模糊糊 寄情影书"
baseurl: ""
url: "http://www.shiningemail.com/"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "LiEmail"
  email: shininglm@gmail.com
  bio: "Li不清的记忆宫殿"

# Data
gavatar: http://img3.doubanio.com/icon/ul57126455-8.jpg
favicon: img/favicon.ico

douban_username: 57126455  
twitter_username: 
github_username: LiEmail
facebook_username: Li Miao
weibo_username: u/2538292814  
zhihu_username: li-miao-35

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Azeril"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : LiEmail
  disqus :
      short_name : LiEmail

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation